"""Bulletin Text Field

Revision ID: 2f2e64e3e8a0
Revises: da4d9c9ec424
Create Date: 2023-12-09 07:56:09.223771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f2e64e3e8a0'
down_revision: Union[str, None] = 'da4d9c9ec424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin', sa.Column('bulletin_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin', 'bulletin_text')
    # ### end Alembic commands ###
