"""Fix longitude decimal field

Revision ID: 345edad6d6a7
Revises: 787eab73f513
Create Date: 2023-12-07 12:58:50.083354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '345edad6d6a7'
down_revision: Union[str, None] = '787eab73f513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquake', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Numeric(precision=9, scale=7),
               existing_nullable=False)
    op.alter_column('earthquake', 'longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=7),
               type_=sa.Numeric(precision=10, scale=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquake', 'longitude',
               existing_type=sa.Numeric(precision=10, scale=7),
               type_=mysql.DECIMAL(precision=9, scale=7),
               existing_nullable=False)
    op.alter_column('earthquake', 'latitude',
               existing_type=sa.Numeric(precision=9, scale=7),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
    # ### end Alembic commands ###
