"""Separate earthquakes and bulletins

Revision ID: 54e22835e028
Revises: b4a15fea946f
Create Date: 2023-12-07 10:12:47.963338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54e22835e028'
down_revision: Union[str, None] = 'b4a15fea946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuscategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['statuscategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earthquake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wmo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('depth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=7), nullable=False),
    sa.Column('magnitude', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('origin_time', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earthquake_id', sa.Integer(), nullable=False),
    sa.Column('issue_time', sa.DateTime(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('wmo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_php', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['earthquake_id'], ['earthquake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tsunamibulletin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tsunamibulletin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('wmo_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('twc_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('twc_event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('origin_time', mysql.DATETIME(), nullable=False),
    sa.Column('event_lat', mysql.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('event_lon', mysql.DECIMAL(precision=9, scale=7), nullable=False),
    sa.Column('event_magnitude', mysql.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('event_magnitude_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_depth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_depth_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quake_location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bulletin_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bulletin_issue_time', mysql.DATETIME(), nullable=False),
    sa.Column('bulletin_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ingestion_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('bulletin')
    op.drop_table('earthquake')
    op.drop_table('status')
    op.drop_table('statuscategory')
    # ### end Alembic commands ###
