"""Bulletin Status Field

Revision ID: 663fd51ec409
Revises: d207e09714a8
Create Date: 2023-12-09 14:56:57.847636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '663fd51ec409'
down_revision: Union[str, None] = 'd207e09714a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin', sa.Column('status_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin', 'status_id')
    # ### end Alembic commands ###
