"""Bulletin Status Field Foreign Key

Revision ID: 6cec135daf8b
Revises: 663fd51ec409
Create Date: 2023-12-09 15:02:49.320951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cec135daf8b'
down_revision: Union[str, None] = '663fd51ec409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bulletin', 'bulletinstatus', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bulletin', type_='foreignkey')
    # ### end Alembic commands ###
