"""Add bulletin discovery time

Revision ID: 787eab73f513
Revises: 345ccfa2cb7d
Create Date: 2023-12-07 11:50:19.887791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '787eab73f513'
down_revision: Union[str, None] = '345ccfa2cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin', sa.Column('discovery_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin', 'discovery_time')
    # ### end Alembic commands ###
