"""tsunami bulletin model

Revision ID: b4a15fea946f
Revises: 
Create Date: 2023-12-06 12:28:58.483910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b4a15fea946f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tsunamibulletin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wmo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twc_event_id', sa.Integer(), nullable=False),
    sa.Column('origin_time', sa.DateTime(), nullable=False),
    sa.Column('event_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('event_lon', sa.Numeric(precision=9, scale=7), nullable=False),
    sa.Column('event_magnitude', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('event_magnitude_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_depth', sa.Integer(), nullable=False),
    sa.Column('event_depth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quake_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bulletin_number', sa.Integer(), nullable=False),
    sa.Column('bulletin_issue_time', sa.DateTime(), nullable=False),
    sa.Column('bulletin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tsunamibulletin')
    # ### end Alembic commands ###
