"""Bulletin Status Table

Revision ID: d207e09714a8
Revises: 2f2e64e3e8a0
Create Date: 2023-12-09 14:10:40.194115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd207e09714a8'
down_revision: Union[str, None] = '2f2e64e3e8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

bulletin_status_table = sa.sql.table(
    "bulletinstatus",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String)
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletinstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        bulletin_status_table,
        [
            {
                "id": 1,
                "name": "New"
            },
            {
                "id": 2,
                "name": "Analyzed"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulletinstatus')
    # ### end Alembic commands ###
