"""Optional Bulletin Fields

Revision ID: da4d9c9ec424
Revises: dde07832af2d
Create Date: 2023-12-08 09:07:33.088139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da4d9c9ec424'
down_revision: Union[str, None] = 'dde07832af2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bulletin', 'event_php',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bulletin', 'event_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bulletin', 'event_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bulletin', 'event_php',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
