"""Optional quake fields

Revision ID: dde07832af2d
Revises: 4634782fa9a3
Create Date: 2023-12-08 08:55:20.811533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dde07832af2d'
down_revision: Union[str, None] = '4634782fa9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquake', sa.Column('magnitude_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('earthquake', 'author',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('earthquake', 'category',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquake', 'category',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('earthquake', 'author',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('earthquake', 'magnitude_type')
    # ### end Alembic commands ###
